apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: helium-monitoring
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helium-monitoring
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/hostspaceng/Monitoring.git
      targetRevision: HEAD
      ref: hostspacengRepo
    - repoURL: https://prometheus-community.github.io/helm-charts/
      chart: prometheus
      targetRevision: 19.7.2
      helm:
        valueFiles:
          - $hostspacengRepo/argocd_apps/values/prometheus.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  
  progressDeadlineSeconds: 600